name: 'Log Message'
description: 'Logs a custom message to the console'
inputs:
  message:
    description: 'The message to log'
    required: true
runs:
  using: 'node12'
  main: 'index.js'

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log a custom message
        uses: ./.github/actions/log-message
        with:
          message: 'Hello from custom action!'

