name: Testing Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Downloading the code from repo
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
     